version = 1

test_patterns = [
  "[[analyzers]]",
  "name = \"test-coverage\"",
  "enabled = true"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"